name: Publish gem

on:
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    environment: rubygems

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-4.0.1
          bundler-cache: false

      - name: Release gem
        uses: rubygems/release-gem@v1
        with:
          setup-ruby: false

