name: Publish gem

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    environment: rubygems

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-4.0.1

      - name: Build gem
        run: gem build brevo-extras.gemspec

      - name: Push to RubyGems
        run: gem push brevo-extras-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
